apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sre-bible
  namespace: sre-bible
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - sre.bible
      secretName: sre-bible-tls
  rules:
    - host: sre.bible
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sre-bible
                port:
                  name: http
