apiVersion: v1
kind: ServiceAccount
metadata:
  name: sre-bible
  namespace: sre-bible
  annotations:
    iam.gke.io/gcp-service-account: sre-bible-proxy@gen-lang-client-0479899208.iam.gserviceaccount.com
